# Generated by Django 2.0.3 on 2018-06-14 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('datetime', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField(editable=False)),
                ('json_config', models.TextField()),
                ('time_taken', models.FloatField()),
                ('num_bought_won', models.IntegerField()),
                ('num_sold_won', models.IntegerField()),
                ('num_bought_failed', models.IntegerField()),
                ('num_sold_failed', models.IntegerField()),
                ('exp_profit', models.TextField()),
                ('linear_profit', models.IntegerField()),
                ('lowest_balance', models.IntegerField()),
                ('starting_balance', models.IntegerField()),
            ],
        ),
    ]
