# Generated by Django 2.0.3 on 2018-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180614_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='exp_profit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='linear_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='lowest_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='num_bought_failed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='num_bought_won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='num_sold_failed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='num_sold_won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='starting_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
